AHM.Logistic.Smart.WebUI/AHM_LOGISTIC_SMART_ADM/Controllers/PersonsController.cs
using AHM.Logistic.Smart.Common.Models;
using AHM_LOGISTIC_SMART_ADM.Models;
using AHM_LOGISTIC_SMART_ADM.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AHM_LOGISTIC_SMART_ADM.Controllers
{
    public class PersonsController : Controller
    {
        private readonly CatalogService _catalogService;

        public PersonsController(CatalogService catalogService)
        {
            _catalogService = catalogService;
        }

        public async Task<IActionResult> Index()
        {
            var model = new List<PersonsViewModel>();
            var list = await _catalogService.PersonsList(model);

            return View(list.Data);
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int Id)
        {
            var result = await _catalogService.PersonsDetails(Id);
            return Json(result);
        }

        #region Lists
        [HttpGet]
        public async Task<IActionResult> PersonsList()
        {
            var model = new List<AHM.Logistic.Smart.Common.Models.PersonsViewModel>();
            var result = await _catalogService.PersonsList(model);
            return Json(result);
        }

        [HttpGet]
        public async Task<IActionResult> DepartList()
        {
            var model = new List<AHM.Logistic.Smart.Common.Models.DepartmentsViewModel>();
            var result = await _catalogService.ApiDepartmentsList(model);
            return Json(result);
        }

        [HttpGet]
        public async Task<IActionResult> MunList(int id)
        {
            var model = new List<AHM.Logistic.Smart.Common.Models.MunicipalitiesViewModel>();
            var result = await _catalogService.MunicipalitiesList(model);
            return Json(result);
        }
        #endregion

        [HttpGet]
        public IActionResult Create()
        {
            var model = new PersonsModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(PersonsModel model)
        {
            var result = await _catalogService.InsertPersons(model);
            return Json(result);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var response = await _catalogService.PersonsDetails(id);
            return View(response.Data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(PersonsViewModel model)
        {
            var result = await _catalogService.EditPersons(model);
            return Json(result);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int Id, int Mod)
        {
            var result = await _catalogService.DeletePersons(Id, Mod);
            return Json(result);
        }
    }
}

AHM.Logistic.Smart.WebUI/AHM_LOGISTIC_SMART_ADM/Views/Persons/Create.cshtml
@model AHM.Logistic.Smart.Common.Models.PersonsModel
@{
    ViewData["Title"] = "Crear Persons";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-content-wrapper">
    <div class="row">
        <div class="col-md-12">
            <div class="card m-b-30">
                <div class="card-body">
                    <h4 class="card-title font-16 mt-0">Registrar Persons</h4>
                    <h6 class="card-subtitle font-14 text-muted">Support card subtitle</h6>
                    <div class="card-body">
                        <form method="post" autocomplete="off" id="frmCreatePersons">
                            <div class="row">
                                <input type="hidden" asp-for="per_IdUserCreate" value="1" />
                                <div class="form-group col-md-6">
                                    <label class="form-label">Identidad</label>
                                    <input type="text" asp-for="per_Identidad" class="form-control" maxlength="14" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Primer Nombre</label>
                                    <input type="text" asp-for="per_Firstname" class="form-control" maxlength="30" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Segundo Nombre</label>
                                    <input type="text" asp-for="per_Secondname" class="form-control" maxlength="30" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Apellidos</label>
                                    <input type="text" asp-for="per_LastNames" class="form-control" maxlength="30" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Fecha de nacimiento</label>
                                    <input type="date" asp-for="per_BirthDate" class="form-control" value="dd-mm-yyyy"/>
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Sexo</label>
                                    <select asp-for="per_Sex" class="form-control">
                                        <option value="0">Por favor seleccione una opción... </option>
                                        <option value="F">Femenino</option>
                                        <option value="M">Masculino</option>
                                    </select>
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Email</label>
                                    <input type="email" asp-for="per_Email" class="form-control" maxlength="50" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Teléfono</label>
                                    <input type="text" asp-for="per_Phone" class="form-control" maxlength="11" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Dirección</label>
                                    <input type="text" asp-for="per_Direccion" class="form-control" maxlength="70" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Departamento</label>
                                    <select name="dep_Id" id="SelectDepartments" class="form-control" maxlength="1"></select>
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Municipio</label>
                                    <select name="mun_Id" id="SelectMunicipalities" class="form-control" maxlength="1" disabled>
                                        <option value="0"> Por favor seleccione una opción... </option>
                                    </select>
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Estado Civil</label>
                                    <select asp-for="per_Esciv" class="form-control">
                                        <option value="0">Por favor seleccione una opción... </option>
                                        <option value="default">Casado</option>
                                        <option value="S">Soltero</option>
                                        <option value="D">Divorciado</option>
                                        <option value="V">Viudo</option>
                                        <option value="U">Unión Libre</option>
                                    </select>
                                </div>
                            </div>
                                <button type="submit" class="btn btn-secondary" style="margin: 0px 30px 0px 0px;">Agregar</button>
                                <a class="btn btn-primary" asp-area="" asp-controller="Persons" asp-action="Index">Regresar</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/js/jquery.min.js"></script>
<script src="~/js/app/Persons/PersonsCreate.js"></script>
<script src="~/js/app/Persons/Persons.js"></script>
<script>
    function docReady(fn) {
        if (document.readyState === "complete" || document.readyState === "interactive") {
            setTimeout(fn, 1);
        } else {
            document.addEventListener("DOMContentLoaded", fn);
        }
    }
    docReady(function () {
        Menu('persons');

    });
</script>

AHM.Logistic.Smart.WebUI/AHM_LOGISTIC_SMART_ADM/Views/Persons/Delete.cshtml
@model AHM.Logistic.Smart.Common.Models.PersonsViewModel
@{
    ViewData["Title"] = "Eliminar Persons";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="padding-top: 10%">
    <div class="container-fluid content-inner mt-n5 py-0">
        <div>
            <div class="row">
                <div class="col-xl-12 col-lg-12">
                    <div class="card" style="padding: 1%">
                        <div class="card-header d-flex justify-content-between">
                            <div class="header-title">
                                <h4 class="card-title">¿Desea eliminar la persona?</h4>
                            </div>
                            <hr />
                        </div>
                        <div class="card-body">
                            <div class="new-user-info">
                                <form method="post" autocomplete="off">
                                    <div class="row">
                                        <input type="hidden" asp-for="per_IdUserCreate" value="1" />
                                        <input type="hidden" asp-for="per_IdUserModified" value="1" />
                                        <input type="hidden" asp-for="per_Id"/>
                                        <input type="hidden" asp-for="per_Identidad" />
                                        <input type="hidden" asp-for="per_Firstname" />
                                        <input type="hidden" asp-for="per_Secondname" />
                                        <input type="hidden" asp-for="per_LastNames" />
                                        <input type="hidden" asp-for="per_BirthDate" />
                                        <input type="hidden" asp-for="per_Sex" />
                                        <input type="hidden" asp-for="per_Email" />
                                        <input type="hidden" asp-for="per_Phone" />
                                        <input type="hidden" asp-for="per_Direccion" />
                                        <input type="hidden" asp-for="dep_Id" />
                                        <input type="hidden" asp-for="mun_Id" />
                                        <input type="hidden" asp-for="per_Esciv" />
                                    </div>
                                    <hr>
                                    <div style="margin: 4% 0% 0% 0%;">
                                        <button type="submit" class="btn btn-success" style="margin: 0px 30px 0px 0px;">Guardar</button>
                                        <a class="btn btn-outline-secondary" asp-area="" asp-controller="Persons" asp-action="Index">Regresar</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AHM.Logistic.Smart.WebUI/AHM_LOGISTIC_SMART_ADM/Views/Persons/Edit.cshtml
@model AHM.Logistic.Smart.Common.Models.PersonsViewModel
@{
    ViewData["Title"] = "Editar Persons";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-content-wrapper">
    <div class="row">
        <div class="col-md-12">
            <div class="card m-b-30">
                <div class="card-body">
                    <h4 class="card-title font-16 mt-0">Editar Persona</h4>
                    <h6 class="card-subtitle font-14 text-muted">Support card subtitle</h6>
                    <div class="card-body">
                        <form method="post" autocomplete="off" id="frmEditPersons">
                            <div class="row">
                                <input type="hidden" asp-for="per_Id" />
                                <input type="hidden" asp-for="per_IdUserCreate" value="1" />
                                <div class="form-group col-md-6">
                                    <label class="form-label">Identidad</label>
                                    <input type="text" asp-for="per_Identidad" class="form-control" maxlength="14" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Primer Nombre</label>
                                    <input type="text" asp-for="per_Firstname" class="form-control" maxlength="30" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Segundo Nombre</label>
                                    <input type="text" asp-for="per_Secondname" class="form-control" maxlength="30" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Apellidos</label>
                                    <input type="text" asp-for="per_LastNames" class="form-control" maxlength="30" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Fecha de nacimiento</label>
                                    <input type="date" asp-for="per_BirthDate" class="form-control" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Sexo</label>
                                    <select asp-for="per_Sex" class="form-control">
                                        <option value="0">Por favor seleccione una opción... </option>
                                        <option value="F">Femenino</option>
                                        <option value="M">Masculino</option>
                                    </select>
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Email</label>
                                    <input type="email" asp-for="per_Email" class="form-control" maxlength="50" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Teléfono</label>
                                    <input type="text" asp-for="per_Phone" class="form-control" maxlength="11" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Dirección</label>
                                    <input type="text" asp-for="per_Direccion" class="form-control" maxlength="70" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Departamento</label>
                                    <input type="hidden" asp-for="dep_Id" id="departamento" />
                                    <select id="SelectDepartments" class="form-control" maxlength="1"></select>
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Municipio</label>
                                    <input type="hidden" asp-for="mun_Id" id="municipio" />
                                    <select id="SelectMunicipalities" class="form-control" maxlength="1" disabled>
                                        <option value="0"> Por favor seleccione una opción... </option>
                                    </select>
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label">Estado Civil</label>
                                    <select asp-for="per_Esciv" class="form-control">
                                        <option value="0">Por favor seleccione una opción... </option>
                                        <option value="C">Casado</option>
                                        <option value="S">Soltero</option>
                                        <option value="D">Divorciado</option>
                                        <option value="V">Viudo</option>
                                        <option value="U">Union Libre</option>
                                    </select>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-secondary" style="margin: 0px 30px 0px 0px;" id="ConfirmEditPersons">Guardar</button>
                                <a class="btn btn-primary" asp-area="" asp-controller="Persons" asp-action="Index">Regresar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/js/jquery.min.js"></script>
<script src="~/js/app/Persons/PersonsEdit.js"></script>
<script src="~/js/app/Persons/Persons.js"></script>
<script>
    function docReady(fn) {
        if (document.readyState === "complete" || document.readyState === "interactive") {
            setTimeout(fn, 1);
        } else {
            document.addEventListener("DOMContentLoaded", fn);
        }
    }
    docReady(function () {
        Menu('persons');

    });
</script>

AHM.Logistic.Smart.WebUI/AHM_LOGISTIC_SMART_ADM/Views/Persons/Index.cshtml
@model IEnumerable<AHM.Logistic.Smart.Common.Models.PersonsViewModel>
@{
    ViewData["Title"] = "Persona";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Table = "Registro de Personas";
    ViewBag.Description = "Algo vamos a poner aqui";
}

<div class="page-content-wrapper">
    <div class="row">
        <div class="col-12">
            <div class="card m-b-20">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <h4 class="card-title font-16 mt-0">Listado de Personas</h4>
                            <h6 class="card-subtitle font-14 text-muted">Support card subtitle</h6>
                        </div>
                        <div class="col-md-4">
                            <div style="box-sizing:border-box; padding:0px 10px" class="row justify-content-end">
                                <a class="btn btn-primary" asp-controller="Persons" asp-action="Create">Nuevo Registro</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Identidad</th>
                                    <th>Primer Nombre</th>
                                    <th>Segundo Nombre</th>
                                    <th>Apellidos</th>
                                    <th>Fecha Nacimiento</th>
                                    <th>Sexo</th>
                                    <th>Email</th>
                                    <th>Telefono</th>
                                    <th>Dirección</th>
                                    <th>Departamento</th>
                                    <th>Municipios</th>
                                    <th>Estado Civil</th>
                                    <th style="min-width: 100px">Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.per_Id)</td>
                                        <td>@Html.DisplayFor(modelItem => item.per_Identidad)</td>
                                        <td>@Html.DisplayFor(modelItem => item.per_Firstname)</td>
                                        <td>@Html.DisplayFor(modelItem => item.per_Secondname)</td>
                                        <td>@Html.DisplayFor(modelItem => item.per_LastNames)</td>
                                        <td>@Html.DisplayFor(modelItem => item.per_BirthDate)</td>
                                        <td>@Html.DisplayFor(modelItem => item.per_Sex)</td>
                                        <td>@Html.DisplayFor(modelItem => item.per_Email)</td>
                                        <td>@Html.DisplayFor(modelItem => item.per_Phone)</td>
                                        <td>@Html.DisplayFor(modelItem => item.per_Direccion)</td>
                                        <td>@Html.DisplayFor(modelItem => item.dep_Description)</td>
                                        <td>@Html.DisplayFor(modelItem => item.mun_Description)</td>
                                        <td>@Html.DisplayFor(modelItem => item.per_Esciv)</td>


                                        <td style="text-align:center; color: #FFF">
                                            <div class="flex align-items-center list-user-action">
                                                <a class="btn btn-sm btn-icon btn-secondary" data-toggle="tooltip" data-placement="top" title="" data-original-title="Editar" asp-route-id="@item.per_Id" asp-area="" asp-controller="Persons" asp-action="Edit">
                                                    <span class="btn-inner">
                                                        <svg width="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                            <path d="M11.4925 2.78906H7.75349C4.67849 2.78906 2.75049 4.96606 2.75049 8.04806V16.3621C2.75049 19.4441 4.66949 21.6211 7.75349 21.6211H16.5775C19.6625 21.6211 21.5815 19.4441 21.5815 16.3621V12.3341" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M8.82812 10.921L16.3011 3.44799C17.2321 2.51799 18.7411 2.51799 19.6721 3.44799L20.8891 4.66499C21.8201 5.59599 21.8201 7.10599 20.8891 8.03599L13.3801 15.545C12.9731 15.952 12.4211 16.181 11.8451 16.181H8.09912L8.19312 12.401C8.20712 11.845 8.43412 11.315 8.82812 10.921Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                                            <path d="M15.1655 4.60254L19.7315 9.16854" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                                        </svg>
                                                    </span>
                                                </a>
                                                <a class="btn btn-sm btn-icon btn-primary" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete" onclick="DeletePersons(@item.per_Id)">
                                                    <span class="btn-inner">
                                                        <svg width="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="currentColor">
                                                            <path d="M19.3248 9.46826C19.3248 9.46826 18.7818 16.2033 18.4668 19.0403C18.3168 20.3953 17.4798 21.1893 16.1088 21.2143C13.4998 21.2613 10.8878 21.2643 8.27979 21.2093C6.96079 21.1823 6.13779 20.3783 5.99079 19.0473C5.67379 16.1853 5.13379 9.46826 5.13379 9.46826" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                                            <path d="M20.708 6.23975H3.75" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                                            <path d="M17.4406 6.23973C16.6556 6.23973 15.9796 5.68473 15.8256 4.91573L15.5826 3.69973C15.4326 3.13873 14.9246 2.75073 14.3456 2.75073H10.1126C9.53358 2.75073 9.02558 3.13873 8.87558 3.69973L8.63258 4.91573C8.47858 5.68473 7.80258 6.23973 7.01758 6.23973" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                                        </svg>
                                                    </span>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/js/jquery.min.js"></script>
<script src="~/js/app/Persons/PersonsDelete.js"></script>
<script>
    function docReady(fn) {
        if (document.readyState === "complete" || document.readyState === "interactive") {
            setTimeout(fn, 1);
        } else {
            document.addEventListener("DOMContentLoaded", fn);
        }
    }
    docReady(function () {
        Menu('persons');

    });


</script>