AHM.Logistic.Smart.WebUI/AHM_LOGISTIC_SMART_ADM/Controllers/EmployersController.cs
using AHM_LOGISTIC_SMART_ADM.Models;
using AHM_LOGISTIC_SMART_ADM.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AHM.Logistic.Smart.Common.Models;

namespace AHM_LOGISTIC_SMART_ADM.Controllers
{
    public class EmployersController : Controller
    {
        private readonly CatalogService _catalogService;

        public EmployersController(CatalogService catalogService)
        {
            _catalogService = catalogService;
        }
        public async Task<IActionResult> Index()
        {
            var model = new List<AHM.Logistic.Smart.Common.Models.EmployeesViewModel>();
            var list= await _catalogService.EmployeesList(model);
            if (list.Data == null) return RedirectToAction("Error", "Home");
            else return View(list.Data);
        }

        public async Task<IActionResult> EmployeesList()
        {
            var model = new List<AHM.Logistic.Smart.Common.Models.EmployeesViewModel>();
            var result = await _catalogService.EmployeesList(model);
            return Json(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new EmployeesModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(EmployeesModel model)
        {
            var resultado = await _catalogService.InsertEmployees(model);
            return Json(resultado);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var response = await _catalogService.DetailsEmployees(id);
            return Json(response);
        }

        [HttpPut]
        public async Task<IActionResult> Edit(EmployeesModel model, int id)
        {
            var result = await _catalogService.EditEmployees(model, id);
            return Json(result);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int Id, int Mod)
        {
            var result = await _catalogService.DeleteEmployees(Id, Mod);
            return Json(result);
        }
    }
}

AHM.Logistic.Smart.WebUI/AHM_LOGISTIC_SMART_ADM/Views/Employers/Create.cshtml
@model AHM.Logistic.Smart.Common.Models.EmployeesModel
@{
    ViewData["Title"] = "Crear Empleados";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid content-inner mt-n5 py-0">
    <div>
        <div class="row">
            <div class="col-xl-12 col-lg-12">
                <div class="card" style="padding: 1%">
                    <div class="card-header d-flex justify-content-between">
                        <div class="header-title">
                            <h4 class="card-title">Empleadores</h4>
                        </div>
                    </div>
                    <hr />
                    <div class="card-body">
                        <div class="new-user-info">
                            <form method="post" autocomplete="off">
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label class="form-label">Persona</label>
                                        <select name="type" class="selectpicker form-control" data-style="py-0">
                                            <option>Seleccione</option>
                                            <option>Persona</option>
                                            <option>Persona</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label class="form-label">Areas</label>
                                        <select name="type" class="selectpicker form-control" data-style="py-0">
                                            <option>Seleccione</option>
                                            <option>Areas</option>
                                            <option>Areas</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label class="form-label">Ocupación</label>
                                        <select name="type" class="selectpicker form-control" data-style="py-0">
                                            <option>Seleccione</option>
                                            <option>Ocupación</option>
                                            <option>Ocupación</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label class="form-label">Estado</label>
                                        <select name="type" class="selectpicker form-control" data-style="py-0">
                                            <option>Activo</option>
                                            <option>Inactivo</option>
                                        </select>
                                    </div>

                                </div>
                                <hr>
                                <div style="margin: 4% 0% 0% 0%;">
                                    <button type="submit" class="btn btn-success">Agregar</button>
                                    <a class="btn btn-outline-secondary" asp-area="" asp-controller="Employers" asp-action="Index">Regresar</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AHM.Logistic.Smart.WebUI/AHM_LOGISTIC_SMART_ADM/Views/Employers/Edit.cshtml
@{
    ViewData["Title"] = "Editar Empleados";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid content-inner mt-n5 py-0">
    <div>
        <div class="row">
            <div class="col-xl-12 col-lg-12">
                <div class="card" style="padding: 5% 3% 5% 3%">
                    <div class="card-header d-flex justify-content-between">
                        <div class="header-title">
                            <h4 class="card-title">Empleadores</h4>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="new-user-info">
                            <form>
                                <div class="row">
                                    <div class="form-group col-md-6">
                                        <label class="form-label">Persona</label>
                                        <select name="type" class="selectpicker form-control" data-style="py-0">
                                            <option>Seleccione</option>
                                            <option>Persona</option>
                                            <option>Persona</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label class="form-label">Areas</label>
                                        <select name="type" class="selectpicker form-control" data-style="py-0">
                                            <option>Seleccione</option>
                                            <option>Areas</option>
                                            <option>Areas</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label class="form-label">Ocupación</label>
                                        <select name="type" class="selectpicker form-control" data-style="py-0">
                                            <option>Seleccione</option>
                                            <option>Ocupación</option>
                                            <option>Ocupación</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label class="form-label">Estado</label>
                                        <select name="type" class="selectpicker form-control" data-style="py-0">
                                            <option>Activo</option>
                                            <option>Inactivo</option>
                                        </select>
                                    </div>

                                </div>
                                <hr>

                                <div style="margin: 4% 0% 0% 0%;">
                                    <button type="submit" class="btn btn-primary" style="margin: 0px 30px 0px 0px;">Editar</button>
                                    <a class="btn btn-danger" asp-area="" asp-controller="Employers" asp-action="Index">Regresar</a>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AHM.Logistic.Smart.WebUI/AHM_LOGISTIC_SMART_ADM/Views/Employers/Index.cshtml
@model IEnumerable<AHM.Logistic.Smart.Common.Models.EmployeesViewModel>
@{
    ViewData["Title"] = "Empleados";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Table = "Registro de empleados";
    ViewBag.Description = "Algo vamos a poner aqui";
}
<div class="page-content-wrapper">
    <div class="row">
        <div class="col-12">
            <div class="card m-b-20">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <h4 class="card-title font-16 mt-0">Listado de empleados</h4>
                            <h6 class="card-subtitle font-14 text-muted">Support card subtitle</h6>
                        </div>
                        <div class="col-md-4">
                            <div style="box-sizing:border-box; padding:0px 10px" class="row justify-content-end">
                                <button id="AbrirModalEmployees" class="btn btn-primary">Nuevo Registro</button>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Nombre</th>
                                    <th>Apellido</th>
                                    <th>Ocupación</th>
                                    <th>Área asignada</th>
                                    <th style="text-align:center;">Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.emp_Id)</td>
                                        <td>@Html.DisplayFor(modelItem => item.per_Firstname)</td>
                                        <td>@Html.DisplayFor(modelItem => item.per_LastNames)</td>
                                        <td>@Html.DisplayFor(modelItem => item.occ_Description)</td>
                                        <td>@Html.DisplayFor(modelItem => item.are_Description)</td>
                                        <td style="text-align:center; color: #FFF">
                                            <div class="flex align-items-center list-user-action">
                                                <a class="btn btn-sm btn-icon btn-secondary" data-toggle="tooltip" data-placement="top" title="" data-original-title="Editar" onclick="ShowModalEditEmployees(@item.emp_Id)">
                                                    <span class="btn-inner">
                                                        <svg width="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                            <path d="M11.4925 2.78906H7.75349C4.67849 2.78906 2.75049 4.96606 2.75049 8.04806V16.3621C2.75049 19.4441 4.66949 21.6211 7.75349 21.6211H16.5775C19.6625 21.6211 21.5815 19.4441 21.5815 16.3621V12.3341" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M8.82812 10.921L16.3011 3.44799C17.2321 2.51799 18.7411 2.51799 19.6721 3.44799L20.8891 4.66499C21.8201 5.59599 21.8201 7.10599 20.8891 8.03599L13.3801 15.545C12.9731 15.952 12.4211 16.181 11.8451 16.181H8.09912L8.19312 12.401C8.20712 11.845 8.43412 11.315 8.82812 10.921Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                                            <path d="M15.1655 4.60254L19.7315 9.16854" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                                        </svg>
                                                    </span>
                                                </a>
                                                <a class="btn btn-sm btn-icon btn-primary" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete" onclick="DeleteEmployees(@item.emp_Id)">
                                                    <span class="btn-inner">
                                                        <svg width="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="currentColor">
                                                            <path d="M19.3248 9.46826C19.3248 9.46826 18.7818 16.2033 18.4668 19.0403C18.3168 20.3953 17.4798 21.1893 16.1088 21.2143C13.4998 21.2613 10.8878 21.2643 8.27979 21.2093C6.96079 21.1823 6.13779 20.3783 5.99079 19.0473C5.67379 16.1853 5.13379 9.46826 5.13379 9.46826" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                                            <path d="M20.708 6.23975H3.75" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                                            <path d="M17.4406 6.23973C16.6556 6.23973 15.9796 5.68473 15.8256 4.91573L15.5826 3.69973C15.4326 3.13873 14.9246 2.75073 14.3456 2.75073H10.1126C9.53358 2.75073 9.02558 3.13873 8.87558 3.69973L8.63258 4.91573C8.47858 5.68473 7.80258 6.23973 7.01758 6.23973" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                                        </svg>
                                                    </span>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--create employees modal-->
<div id="CrearEmpleado" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title mt-0">Registrar Empleado</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="col-sm-12 form-group">
                    <div>
                        <label class="form-label" for="DropDownPersonas">Selecciona una persona</label>
                        <select class="form-control" id="DropDownPersonas">
                        </select>
                    </div>
                </div>

                <div class="col-sm-12 form-group">
                    <div>
                        <label class="form-label" for="DropDownOcupaciones">Selecciona una ocupación</label>
                        <select class="form-control" id="DropDownOcupaciones">
                        </select>
                    </div>
                </div>

                <div class="col-sm-12 form-group">
                    <div>
                        <label class="form-label" for="DropDownAreas">Selecciona un área</label>
                        <select class="form-control" id="DropDownAreas">
                        </select>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="CrearPersonaConfirmar">Aceptar</button>
                <button type="button" class="btn btn-primary" id="CerrarModal" data-bs-dismiss="modal">Cancelar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--edit employees modal-->

<div id="EditarEmpleado" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title mt-0">Editar Empleado</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label class="form-label" for="DropDownPersonas">Selecciona una persona</label>
                    <div>
                        <select class="form-control" id="DropDownPersonas">
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-label" for="DropDownOcupaciones">Selecciona una ocupación</label>
                    <div>
                        <select class="form-control" id="DropDownOcupaciones">
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-label" for="DropDownAreas">Selecciona un área</label>
                    <div>
                        <select class="form-control" id="DropDownAreas">
                        </select>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="EditarPersonaConfirmar">Aceptar</button>
                <button type="button" class="btn btn-primary" id="CerrarModalEditar" data-bs-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

<script src="~/js/jquery.min.js"></script>
<!-- Employees -->
<script src="~/js/app/Employees/EmployeesEdit.js"></script>
<script src="~/js/app/Employees/EmployeesDelete.js"></script>
<script src="~/js/app/Employees/EmployeesCreate.js"></script>

<script>
    function docReady(fn) {
        if (document.readyState === "complete" || document.readyState === "interactive") {
            setTimeout(fn, 1);
        } else {
            document.addEventListener("DOMContentLoaded", fn);
        }
    }
    docReady(function () {
        Menu('empleados');

    });
</script>